# The CRS used for the output QGIS project file.
# All layers will be reprojected to this CRS.
crs: 'EPSG:3413'

# All extent definitions _must_ be geopandas-readable files containing a single
# polygon in `assets/local_data`
boundaries:
  background: 'background_boundary.geojson'
  data: 'data_boundary.geojson'
